//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clasificadores
    {
        public Clasificadores()
        {
            this.Clasificadores1 = new HashSet<Clasificadores>();
            this.VehiculosDocumentos = new HashSet<VehiculosDocumentos>();
            this.VehiculosLicencias = new HashSet<VehiculosLicencias>();
            this.VencimientosServiciosExternosDetalles = new HashSet<VencimientosServiciosExternosDetalles>();
            this.Personas = new HashSet<Personas>();
            this.Personas1 = new HashSet<Personas>();
            this.Proveedores = new HashSet<Proveedores>();
        }
    
        public int Clas_Id { get; set; }
        public string Clas_Desc { get; set; }
        public string Clas_Abrev { get; set; }
        public string Clas_Tabla { get; set; }
        public string Clas_Detalle { get; set; }
        public bool Clas_DatoOblig { get; set; }
        public Nullable<int> Clas_Padre { get; set; }
        public System.DateTime Clas_FecAlta { get; set; }
        public Nullable<System.DateTime> Clas_FecBaja { get; set; }
        public bool Clas_Interno { get; set; }
        public System.DateTime AudFecha { get; set; }
        public int AudUser { get; set; }
    
        public virtual ICollection<Clasificadores> Clasificadores1 { get; set; }
        public virtual Clasificadores Clasificadores2 { get; set; }
        public virtual SeguridadUsuarios SeguridadUsuarios { get; set; }
        public virtual ICollection<VehiculosDocumentos> VehiculosDocumentos { get; set; }
        public virtual ICollection<VehiculosLicencias> VehiculosLicencias { get; set; }
        public virtual ICollection<VencimientosServiciosExternosDetalles> VencimientosServiciosExternosDetalles { get; set; }
        public virtual ICollection<Personas> Personas { get; set; }
        public virtual ICollection<Personas> Personas1 { get; set; }
        public virtual ICollection<Proveedores> Proveedores { get; set; }
    }
}
