//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        public Proveedores()
        {
            this.Vehiculos = new HashSet<Vehiculos>();
            this.VencimientosServiciosExternos = new HashSet<VencimientosServiciosExternos>();
        }
    
        public int Prov_Id { get; set; }
        public int Per_Id { get; set; }
        public string Prov_Codigo { get; set; }
        public int Clas_ProEst_Id { get; set; }
        public bool Prov_CtaCorriente { get; set; }
        public bool Prov_Propio { get; set; }
        public bool Prov_DatosVerificados { get; set; }
        public string Prov_Obs { get; set; }
        public System.DateTime AudFecha { get; set; }
        public int AudUser { get; set; }
    
        public virtual Clasificadores Clasificadores { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual ICollection<VencimientosServiciosExternos> VencimientosServiciosExternos { get; set; }
        public virtual SeguridadUsuarios SeguridadUsuarios { get; set; }
        public virtual ICollection<Vehiculos> Vehiculos { get; set; }

        
    }
}
