//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguridadUsuariosPaginas
    {
        public int SegUsuPag_Id { get; set; }
        public int SegUsu_Id { get; set; }
        public int SegPag_Id { get; set; }
        public bool SegPagUsu_Ver { get; set; }
        public bool SegPagUsu_Alta { get; set; }
        public bool SegPagUsu_Expo { get; set; }
    
        public virtual SeguridadPaginas SeguridadPaginas { get; set; }
        public virtual SeguridadUsuarios SeguridadUsuarios { get; set; }
    }
}
