//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        public Vehiculos()
        {
            this.VehiculosDocumentos = new HashSet<VehiculosDocumentos>();
            this.VehiculosLicencias = new HashSet<VehiculosLicencias>();
        }
    
        public int Veh_Id { get; set; }
        public string Veh_Patente { get; set; }
        public Nullable<int> Prov_Id { get; set; }
        public System.DateTime Veh_FechaDesde { get; set; }
        public Nullable<System.DateTime> Veh_FechaHasta { get; set; }
        public int Veh_PasajerosCantidad { get; set; }
        public bool Veh_DatosVerificados { get; set; }
        public string Veh_Obs { get; set; }
        public System.DateTime AudFecha { get; set; }
        public int AudUser { get; set; }
    
        public virtual Proveedores Proveedores { get; set; }
        public virtual SeguridadUsuarios SeguridadUsuarios { get; set; }
        public virtual ICollection<VehiculosDocumentos> VehiculosDocumentos { get; set; }
        public virtual ICollection<VehiculosLicencias> VehiculosLicencias { get; set; }
    }
}
