//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculosLicencias
    {
        public int VehLic_Id { get; set; }
        public int Veh_Id { get; set; }
        public int Clas_TipoLicencia_Id { get; set; }
        public System.DateTime VehLic_FechaDesde { get; set; }
        public Nullable<System.DateTime> VehLic_FechaHasta { get; set; }
        public bool GeneraAlerta { get; set; }
        public bool VehLic_DatosVerificados { get; set; }
        public string VehLic_Obs { get; set; }
        public System.DateTime AudFecha { get; set; }
        public int AudUser { get; set; }
    
        public virtual Clasificadores Clasificadores { get; set; }
        public virtual SeguridadUsuarios SeguridadUsuarios { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
