//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculosDocumentos
    {
        public int VehDoc_Id { get; set; }
        public int Veh_Id { get; set; }
        public int Clas_TipoDocumento_Id { get; set; }
        public System.DateTime VehDoc_FechaAprobado { get; set; }
        public Nullable<System.DateTime> VehDoc_FechaVencimiento { get; set; }
        public Nullable<System.DateTime> VehDoc_FechaAviso { get; set; }
        public bool GeneraAlerta { get; set; }
        public string VehDoc_ArchivoAdjunto { get; set; }
        public bool VehDoc_DatosVerificados { get; set; }
        public string VehDoc_Obs { get; set; }
        public System.DateTime AudFecha { get; set; }
        public int AudUser { get; set; }
    
        public virtual Clasificadores Clasificadores { get; set; }
        public virtual SeguridadUsuarios SeguridadUsuarios { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
