//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VencimientosServiciosExternos
    {
        public VencimientosServiciosExternos()
        {
            this.VencimientosServiciosExternosDetalles = new HashSet<VencimientosServiciosExternosDetalles>();
            //this.Proveedores= new HashOne<Proveedores>();
        }

        public int VenSerExt_Id { get; set; }
        public string VenSerExt_Prov_Id { get; set; }
        public string VenSerExt_Identificacion { get; set; }
        public string VenSerExt_Descripcion { get; set; }
        public System.DateTime AudFecha { get; set; }
        public int AudUser { get; set; }

        public virtual Proveedores Proveedores { get; set; }

        public virtual SeguridadUsuarios SeguridadUsuarios { get; set; }
        public virtual ICollection<VencimientosServiciosExternosDetalles> VencimientosServiciosExternosDetalles { get; set; }

       



    }
}
