//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VencimientosServiciosExternosDetalles
    {
        //public VencimientosServiciosExternosDetalles()
        //{
        //    this.VencimientosServiciosExternosDetalles1 = new HashSet<VencimientosServiciosExternos>();

        //}
        public int VenSerExtDet_Id { get; set; }
        public int VenSerExt_Id { get; set; }
        public Nullable<System.DateTime> VenSerExtDet_FechaPagado { get; set; }
        public decimal VenSerExtDet_ValorPagado { get; set; }
        public Nullable<int> Clas_MonedasTipos_Id { get; set; }
        public System.DateTime VenSerExtDet_FechaVencimiento { get; set; }
        public string VenSerExtDet_Obs { get; set; }
        public System.DateTime AudFecha { get; set; }
        public int AudUser { get; set; }
    
        public virtual Clasificadores Clasificadores { get; set; }
        public virtual SeguridadUsuarios SeguridadUsuarios { get; set; }
        public virtual VencimientosServiciosExternos VencimientosServiciosExternos { get; set; }

        //public virtual ICollection<VencimientosServiciosExternos> VencimientosServiciosExternosDetalles1 { get; set; }


    }
}
